### ISSUE TITLE
bento.js: What is it?

### ISSUE THREAD

**Issue by boussou** [bentojs/api-core#21]
Hi, can you provide a quick overview of the framework you are building?

I saw you are using modern js (ie yield), that you provide some ACL module,API module,  there are some Dockerfiles.

I would be interested in having a simple page showing :
- your technology stack
- the goal of this project (maybe it is just because of a new web app)
- an rough overview of your roadmap

Please take five minutes to provide an overview.
thanks

**Comment by Kodemon** [comment]
Hi @boussou 

So in the past year or so we have been working on building a set of frameworks specifically designed to build products as quickly as possible without sacrificing base quality. We find ourselves copying code from previous projects into new ones, tweak the code for the new project and watch all our previous work go outdated with small iterative improvements from project to project. When you are going back to an older project to add new features or improvements you find yourself wishing that your first version of a piece of code was coherent with the latest version. This is one of the things we wished to solve.

To solve it we have been going for a modular approach, so you may build a module that improves over time. Not only does your current project benefit from this growth in quality but your previous projects would as well with minimal need to change implementation.

We are currently working on a overview page and documentation. We are also working on getting our [API base to version 1.6](https://github.com/bentojs/api/issues/21) along with [Web base to version 1.0](https://github.com/bentojs/web/issues/6) which will tie up our full stack solution for product development.

We are working hard on this everyday, and our current goal is to get everything into stable release state so that it can be utilized by any developer who wishes to take advantages of the frameworks we are building. We are going at this fully open sourced and welcome any feedback and improvements provided by the community.

I will update this ticket with appropriate links when we get the bentojs website and its documentation in place.

**Comment by boussou** [comment]
Awesome.

It appears to be promising, I starred it & will follow your work.
